#!/usr/bin/env bash

dest=/var/lib/machines/"$1"
if [[ ! -d "$dest" ]]
then
 mkdir "$dest"
 debootstrap --arch=amd64 "$2" "$dest"
 systemd-nspawn -D "$dest" --machine="$1" --network-bridge=br0
else
 systemd-nspawn -D "$dest" --machine="$1" --network-bridge=br0 -b
fi
